# Use Node.js as the base image
FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application’s code
COPY . .

# Build the React application
RUN npm run build

# Use an Nginx server to serve the build files
FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html

# Expose the port Nginx will serve on
EXPOSE 80

# Run Nginx server
CMD ["nginx", "-g", "daemon off;"]
