version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: backend
    ports:
      - "8080:8080" # Map the backend service to port 8080
    networks:
      - app-network
    environment:
      - TEST_KEY=TEST_VALUE

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: frontend
    ports:
      - "3000:80" # Map the frontend service to port 3000
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
